### ISSUE TITLE
Code check configuration file - codecheck.yml

### ISSUE THREAD

**Issue by nuest** [codecheckers/discussion#3]
## Some ideas for future elements

```
command: "..." # for rare cases where user needs to define this, but normally should be auto-generated from format

checks: # there may be multiple checks?
  - ...
 
codechecker:
  check_runner: "mybinder.org" # who executed the check
  check_signature: "..." # something crpytographic?!
```

**Comment by nuest** [comment]
Each author MAY also have a `role` node with a suitable value from the [MARC Code List for Relators](https://www.loc.gov/marc/relators/relaterm.html), such as `aut` for Author, `ctb` for contributor, `dtc` for data contributor, `fnd` for funder, `ths` for thesis advisor, or `cph` for copyright holder.

```yaml
authors:
  - name: Josiah Carberry
    ORCID: 0000-0002-1825-0097
    role: aut
  - name: John Doe
    role: ctb
  - name: ACME Inc. Corp.
    role: cph
```

**Comment by mstimberg** [comment]
Another relevant field might be the licence of the original code (and possibly a separate licence for the codecheck?). Not sure how much flexibility would be needed, e.g. one licence for the code and one for the data? Or even licences for individual files (optionally, of course) – might be necessary if they have been included from elsewhere. And a licence could be either described by its [SPDX identifer](https://spdx.org/licenses/) or by a file in the repository (e.g. with `license` or `license_file` keys as in [conda metadata](https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html)).

**Comment by nuest** [comment]
@angelina-momin With your latest changes to the register generation code, do you see the need to update the specification for `codecheck.yml` files?

Currently it reads:

![image](https://github.com/user-attachments/assets/dd4030e7-f0a4-48a6-945e-44791d78fc7a)

Now we have changed all existing ones to use DOIs, but "only text" still works, right? It's just that if there is text, we do not try to extract a URL from it. I would update the wording to make this limitation clear in the specification, roughly in this direction:

> A reference to the article MUST be provided in `reference`.
> The reference SHOULD be a resolvable URL, preferably a DOI for long-term availability.
> If the reference field contains only a URL, it SHOULD be used to create a link to the paper by implementing tools. The [CODECHECK Register]() does this. If the reference field contains a URL within text, it CAN be extracted, but one should not rely on it.

**Comment by nuest** [comment]
We can also try to make progression of manuscripts through the publishing process more transparent.

In some cases, we check a preprint that is eventually published in a journal, see, e.g., https://github.com/codecheckers/leba-manuscript/commit/06e9a82da9a29a6edea1307ffbee050ee0a40cbb

How can we preserve what was checked and still show that checks appear in journals (even ones who we are not collaborating with).

I think the following would not break the meaning of the existing values/config files:

```yml
reference: <URL, ideally DOI, of the checked manuscript, e.g., a preprint>
publisher-reference: <DOI of the published manuscript>
```

The certificate landing page can link to both, the listings in the register overview table should probably link to reference to not break current things.

**Comment by nuest** [comment]
`report:` should probably be `certificate:`, to get the language straight. "The report is a certificate of executable computation..." seems a bit inconsistent.

**Comment by nuest** [comment]
Add typed links (optional) to capture resources around the whole workflow:

```yml
links:
  - label: primary data repository
    url: https://doi.org/...
    type: data
  - label:  output data
    url: https://doi.org/...
    type: data
  - label: software repository
    url: https://github.com
    type: code
  - label: software archive
    url: https://swhid:123abc
    type: swh
  - label: computational notebook
    url: https://mybinder.org/...
    type: binder
  - label: workflow
  - url: https://usegalaxy.org/....
```

This possibly deprecates the `repository:` field?

Will "label" be a predefined list, or do we need an extra "type" property for each item?
A type could also be used for icons.

One type could also be `preprint` and effectively solve https://github.com/codecheckers/discussion/issues/7.

There should also be a way to capture links like the following ones, which are datasets in 4TU.ResearchData that have a "code works" badge, even if they might be duplicating the `repository` field:

- https://data.4tu.nl/datasets/2c221b54-a20b-4659-99d2-af4a9a114b60/2
- https://data.4tu.nl/datasets/e64c61d3-deb5-4aad-af60-92d92755781f/3
- https://data.4tu.nl/datasets/e06f14b2-d884-4d1a-88fd-4ee8ebc3a98e/1
- https://data.4tu.nl/datasets/319168f0-bc62-4051-84c2-f32718c05386/1
